### ISSUE TITLE
E-mail gathering on person object

### ISSUE THREAD

**Issue by scoudeville** [Dormilich/ripedb-client#11]
Hello,

I experience problem when getting person objects : no e-mail is gathered.

Test code : 
```
$ripe->search($nichdl) ;
$res = $ripe->getResult() ;
```

Returned result is an empty Array: 
```
            [e-mail] => Dormilich\WebService\RIPE\Attribute Object
                (
                    [name:protected] => e-mail
                    [value:protected] => Array
                        (
                        )

                    [mandatory:protected] => 
                    [multiple:protected] => 1
                )
```

Maybe RPSL has been updated by the RIPE ?

Thank you in advance.

**Comment by Dormilich** [comment]
Hello scoudeville,

In a `Person` object the `e-mail` field is optional and hence can be an empty array (since it's also a `multiple` field). 

[Description of the PERSON Object](https://www.ripe.net/manage-ips-and-asns/db/support/documentation/ripe-database-documentation/rpsl-object-types/4-3-descriptions-of-secondary-objects/4-3-6-description-of-the-person-object)

**Comment by Dormilich** [comment]
You can also use the `read()` method to fetch the `Person` object directly.

**Comment by scoudeville** [comment]
Hello Dormilich,

Thank you for you help.
So, if I understand correctly, the search() method doesn't gather the integrality of the object.

But, with the read() method : threre's no problem anymore!

Thanks a lot.

**Comment by Dormilich** [comment]
> So, if I understand correctly, the search() method doesn't gather the integrality of the object.

Both methods merely consume the [RIPE WHOIS REST API](https://github.com/RIPE-NCC/whois) and there is no validation done while parsing the response (validation is only done before you submit an object to the WHOIS API).

Whether the result differs for a _search_ or _read_ request would be a question for the RIPE tech support.
